swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /

# Paths supported by the server application
paths:
  /nest:
    get:
      tags:
        - Server
      operationId: api.server.serve_home
      summary: Serves the index.html
      description: Serves the index.html          
      produces:
        - text/html   
      responses:
        200:
          description: Successfully loaded html page.

  /nest/{filename}:
    get:
      tags:
        - Server
      operationId: api.server.serve_file
      summary: Serves the html files
      description: Serves the html files
      parameters:
        - name: filename
          in: path
          description: file path to download
          required: True
          type: string
      produces:
        - text/html
      responses:
        200:
          description: Successfully loaded html page.

  /graph:
    put:
      operationId: api.graph.create
      tags:
        - Graph
      summary: Crates a new graph view based on active directory ID
      description: Crates a new graph view based on active directory ID
      parameters:
        - name: adid
          in: query
          description: Database ID of the Active Directory root
          required: False
          type: string
            
      responses:
        200:
          description: Returns the graph ID if creation is sucsessfull
          schema:
            type: integer
  
  /graph/{graphid}/query/path:
    get:
      operationId: api.graph.query_path
      tags:
        - Graph
      summary: Performs a shortest path query, listing all shortest paths from src to dst
      description: Performs a shortest path query, listing all shortest paths from src to dst. You may omit either of the parameters, but not both.
      parameters:
        - name: graphid
          in: path
          description: ID of the graph view
          type: integer
          required: True
        - name: src
          in: query
          description: source object SID
          type: string
          required: False
        - name: dst
          in: query
          description: destination object SID
          type: string
          required: False
      responses:
        200:
          description: Returns the graph data with all the shortest paths between the two SIDs
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /graph/{graphid}/query/path/all:
    get:
      operationId: api.graph.query_path_all
      tags:
        - Graph
      summary: Serves the whole graph view data with all nodes and edges
      description: Serves the whole graph view data  with all nodes and edges
      parameters:
        - name: graphid
          in: path
          description: ID of the graph view
          type: integer
          required: True
      responses:
        200:
          description: Returns graph view data with all the nodes and edges
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /graph/{graphid}/node/{nodeid}:
    get:
      operationId: api.graph.get_node
      tags:
        - Graph
      summary: Gets information of a node in the selected graph view
      description: Gets information of a node in the selected graph view
      parameters:
        - name: graphid
          in: path
          description: ID of the graph view
          type: integer
          required: True
        - name: nodeid
          in: path
          description: ID of the node
          type: string
          required: True
      responses:
        200:
          description: Returns full node information
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /graph/{graphid}/nodes/:
    get:
      operationId: api.graph.list_nodes
      tags:
        - Graph
      summary: Fetches a list of all nodes in the graph view
      description: Fetches a list of all nodes in the graph view
      parameters:
        - name: graphid
          in: path
          description: ID of the graph
          type: integer
          required: True
      responses:
        200:
          description: Returns all nodes in the selected graph view
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /graph/{graphid}:
    get:
      operationId: api.graph.get
      tags:
        - Graph
      summary: ONLY FOR TESTING! Returns the FULL graph view selected by graphid
      description: Returns the FULL graph view selected by graphid
      parameters:
        - name: graphid
          in: path
          description: ID of the graph view
          type: integer
          required: True
      responses:
        200:
          description: Returns all nodes and edges in the selected graph view
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

    delete:
      operationId: api.graph.delete
      tags:
        - Graph
      summary: Remove graph view from memory
      description: Delete a graph view from memory
      parameters:
        - name: graphid
          in: path
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted the graph


  /domain/list:
    get:
      operationId: api.domain.list_domains
      tags:
        - Domain
      summary: Returs the list of available domains with basic info
      description: Returs the list of available domains with basic info
      responses:
        200:
          description: List of domain info metadata
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /domain/by_id/{domainid}:
    get:
      operationId: api.domain.get
      tags:
        - Domain
      summary: Returs the full information of a given domain
      description: Returs the full information of a given domain
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
      responses:
        200:
          description: Domain info
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /user/{domainid}/list:
    get:
      operationId: api.user.list_users
      tags:
        - User
      summary: Returs the list of available users for the given domain id
      description: Returs the list of available users for the given domain id
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
      responses:
        200:
          description: List of user info metadata
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /user/{domainid}/by_sid/{usersid}:
    get:
      operationId: api.user.get_sid
      tags:
        - User
      summary: Returs the full information of a given user identified by SID
      description: Returs the full information of a given user identified by SID
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
        - name: usersid
          in: path
          description: SID of the user
          type: string
          required: True
      responses:
        200:
          description: User info
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /user/{domainid}/by_id/{userid}:
    get:
      operationId: api.user.get
      tags:
        - User
      summary: Returs the full information of a given user identified by userid
      description: Returs the full information of a given user identified by userid
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
        - name: userid
          in: path
          description: ID of the user
          type: integer
          required: True
      responses:
        200:
          description: User info
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /machine/{domainid}/list:
    get:
      operationId: api.machine.list_machines
      tags:
        - Machine
      summary: Returs the list of available machines
      description: Returs the list of available machines
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
      responses:
        200:
          description: List of Machine info metadata
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /machine/{domainid}/by_sid/{sid}:
    get:
      operationId: api.machine.get_sid
      tags:
        - Machine
      summary: Returs the full information of a given machine identified by SID
      description: Returs the full information of a given machine identified by SID
      parameters:
        - name: domainid
          in: path
          description: ID of the graph
          type: integer
          required: True
        - name: sid
          in: path
          description: SID of the machine
          type: string
          required: True
      responses:
        200:
          description: Machine info
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /machine/{domainid}/by_id/{machineid}:
    get:
      operationId: api.machine.get
      tags:
        - Machine
      summary: Returs the full information of a given machine identified by id
      description: Returs the full information of a given machine identified by id
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
        - name: machineid
          in: path
          description: ID of the machine
          type: integer
          required: True
      responses:
        200:
          description: Machine info
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO


  /group/{domainid}/list:
    get:
      operationId: api.group.list_groups
      tags:
        - Group
      summary: Returs the list of available groups
      description: Returs the list of available groups
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
      responses:
        200:
          description: List of Group info metadata
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /group/{domainid}/by_sid/{sid}:
    get:
      operationId: api.group.get_sid
      tags:
        - Group
      summary: Returs the full information of a given group identified by SID
      description: Returs the full information of a given group identified by SID
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
        - name: sid
          in: path
          description: SID of the group
          type: string
          required: True
      responses:
        200:
          description: Group info
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /group/{domainid}/by_id/{groupid}:
    get:
      operationId: api.group.get
      tags:
        - Group
      summary: Returs the full information of a given group identified by id
      description: Returs the full information of a given group identified by id
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
        - name: groupid
          in: path
          description: ID of the group
          type: integer
          required: True
      responses:
        200:
          description: Group info
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /ou/{domainid}/list:
    get:
      operationId: api.ou.list_ous
      tags:
        - OU
      summary: Returs the list of available OUs
      description: Returs the list of available OUs
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
      responses:
        200:
          description: List of OU metadata
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /ou/{domainid}/by_guid/{guid}:
    get:
      operationId: api.ou.get_guid
      tags:
        - OU
      summary: Returs the full information of a given group identified by GUID
      description: Returs the full information of a given group identified by GUID
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
        - name: guid
          in: path
          description: GUID of the OU
          type: string
          required: True
      responses:
        200:
          description: OU info
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO

  /ou/{domainid}/by_id/{ouid}:
    get:
      operationId: api.ou.get
      tags:
        - OU
      summary: Returs the full information of a given OU identified by id
      description: Returs the full information of a given OU identified by id
      parameters:
        - name: domainid
          in: path
          description: ID of the domain
          type: integer
          required: True
        - name: ouid
          in: path
          description: ID of the OU
          type: integer
          required: True
      responses:
        200:
          description: OU info
          schema:
            type: object
            properties:
              graph:
                type: string
                description: Placeholder TODO
